const fs = require('fs');

const config = {
  SUPABASE_URL: process.env.SUPABASE_URL || '',
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || '',
};

const content = `// Auto-generated by build.js
const CONFIG = ${JSON.stringify(config, null, 2)};
`;

fs.writeFileSync('./js/config.js', content);
console.log('config.js generated');
